relevate_web_app/apps/styleguide/urls.py
from django.conf.urls import url
from django.contrib.auth import views as django_auth_views
from .examples import examples
from .views import styleguide_views

urlpatterns = []
for example in examples:
  urlpatterns.append(url(r'' + example, styleguide_views.StyleguideView.as_view(), name=example))

urlpatterns.append(url(r'', styleguide_views.StyleguideView.as_view(), name='index'))

relevate_web_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers


urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^', include('apps.contribution.urls', namespace='contribution')),
	url(r'^profile/', include('apps.profiles.urls', namespace='profile')),
	url(r'^', include('django.contrib.auth.urls')),
	url(r'^api/', include('apps.api.urls', namespace='api')),
	url(r'^styleguide/', include('apps.styleguide.urls', namespace='styleguide')),
	#required for ckeditor file upload
	url(r'^ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

relevate_web_app/apps/styleguide/views/styleguide_views.py
from django.shortcuts import render
from django.views.generic import View
from ..examples import examplesData
import string

class StyleguideView(View):
  def get(self, request):
    for data in examplesData:
      if data.rawName in request.path:
        return render(request, 'examples/' + data.rawName + '.html', {'examplesData': examplesData, 'displayName': data.displayName, 'cssFilePath': data.cssFilePath, 'jsFilePath':data.jsFilePath})

    return render(request, 'index.html', {'examplesData': examplesData})

relevate_web_app/apps/styleguide/templates/partials/nav_partial.html
{% load icon_tags %}

<div class="rv-styleguide-nav">
  <div class="rv-styleguide-nav_logo-container">
    <a class="rv-styleguide-nav_logo" href="{% url 'styleguide:index' %}" tabindex="-1" aria-hidden="true">
      {% icon_relevate_logo title="logo" color="inverse" size="large" %}
    </a>
    <a class="rv-styleguide-nav_logo-caption" href="{% url 'styleguide:index' %}">
      <h3 class="rv-styleguide-nav_logo-caption--header">Styleguide</h3>
    </a>
  </div>
  <div class="rv-styleguide-nav_links-container">
    {% for data in examplesData %}
      <a
        class="rv-styleguide-nav_link {% ifequal data.displayName displayName %} selected {% endifequal %}"
        href="{% url 'styleguide:'|add:data.rawName %}"
      >
        {{data.displayName}}
      </a>
    {% endfor %}
  </div>
</div>